### ISSUE TITLE
PoAmProjector not giving any results

### ISSUE THREAD

**Issue by bengouts** [danbelsky/DunedinPACE#1]
Hi, 

Thanks for this package. 

Unfortunately, I am not able to get any results from the function PoAmProjector, while my data covers >95% of required probes. I also checked the formatted input type. Do you know what I'm doing wrong ?

You can find attached [attached](https://github.com/danbelsky/DunedinPACE/files/8773701/DunedinPACE_test.csv) the data, and the code I used : 

```
library(DunedinPACE)
betas = read.table("DunedinPACE_test.csv", h=T)
colMeans(is.na(betas))
PoAmProjector(betas)
```

(R4.1.1, DunedinPACE 0.1.1)

Thanks a lot for your help,
Benoit

**Comment by ghost** [comment]
Hi Benoit,

For DunedinPACE, we actually use 20k probes to 're-normalize' the data to the original cohort that the aging metric is derived from, so you actually need >80% of the 20k probes.

You can see a full list of probes necessary to calculate the score by running here:

`getRequiredProbes(backgroundList=T)`

Best,
-David

**Comment by bengouts** [comment]
Thank you a lot for your quick answer !
I did not get that, but now you mention that, it makes perfect sense !🙂
Benoit
