### ISSUE TITLE
typo in ./R/PoAmProjector.R breaks the PoAmProjector() function

### ISSUE THREAD

**Issue by hhp94** [danbelsky/DunedinPACE#15]
Line 15, `./R/PoAmProjector.R.` `requireNamespace(preprocessCore)` should be changed to `requireNamespace("preprocessCore")`. Otherwise the function `PoAmProjector()` would return an error `preprocessCore object not found`. 

System info:
R 4.2.1
DunedinPACE version: e4cd508f63c573d71895b28e2e449846a7a11f8a
OS: windows 10

EDIT: added file in reference

**Comment by hhp94** [comment]
Also, related to this issue. Line 71 `normalize.quantiles.use.target` in `./R/PoAmProjector.R` threw an error for me: of `could not find function "normalize.quantiles.use.target"`. Changing this to explicitly calls `preprocessCore::normalize.quantiles.use.target()` fixed my issue

**Comment by CPRyan** [comment]
Thanks for your feedback @hhp94. This is the first time I've heard of these being an issue, we have addressed them to prevent anyone else having problems in the future.
