### ISSUE TITLE
Compatible with Infinium MethylationEPIC v2.0?

### ISSUE THREAD

**Issue by schipma** [danbelsky/DunedinPACE#25]
Hello,

Is DunedinPACE compatible with the new Infinium MethylationEPIC v2.0 chip?

Thanks!

**Comment by CPRyan** [comment]
Good question: 

Of the 173 PACE probes, it looks like 29 are missing from EPIC V2. All DunedinPACE probes will be present on the new MSA array. 

DunedinPACE also uses about 20k probes to harmonize methylation values with DNAm from the original cohort where PACE was constructed. 

Many of these will be missing from the new EPIC V2 and MSA, but we are working on updating DunedinPACE to do a similar thing with different probes. This will hopefully be reflected in upcoming versions of the package. 

Calen

**Comment by schipma** [comment]
Thank you for your prompt response, Calen!

Matt

--
Matthew J. Schipma PhD
Associate Director NUSeq
Associate Technical Director QDSC

** Data Retention Policy:

The NUSeq and QDSC core facilities use SharePoint as the primary mechanism for delivering genomics data to users.  Due to space limitations, a data retention policy is in effect in which the core facility will maintain project data for a period of 6 months from the date that the project data is first made available.  It is expected that users will retrieve all their project data within that 6-month period and maintain it.  If a project requires further processing by the core facility after the 6 months have expired, it is the responsibility of the user to provide a copy of all files required.


From: Calen Patrick Ryan, PhD ***@***.***>
Date: Tuesday, January 31, 2023 at 7:25 PM
To: danbelsky/DunedinPACE ***@***.***>
Cc: Matthew John Schipma ***@***.***>, Author ***@***.***>
Subject: Re: [danbelsky/DunedinPACE] Compatible with Infinium MethylationEPIC v2.0? (Issue #25)

Good question:

Of the 173 PACE probes, it looks like 29 are missing from EPIC V2. All DunedinPACE probes will be present on the new MSA array.

DunedinPACE also uses about 20k probes to harmonize methylation values with DNAm from the original cohort where PACE was constructed.

Many of these will be missing from the new EPIC V2 and MSA, but we are working on updating DunedinPACE to do a similar thing with different probes. This will hopefully be reflected in upcoming versions of the package.

Calen

**Comment by longevityboris** [comment]
Hello,

> PACEProjector(beta_matrix)
$DunedinPACE
X207096540004_R01C01 X207096540004_R02C01 X207096540004_R03C01 X207096540004_R04C01 X207096540004_R05C01 X207096540004_R06C01 X207096540004_R07C01 X207096540004_R08C01 
                  NA                   NA                   NA                   NA                   NA                   NA                   NA                   NA 

Looks like my Epic v2 data cannot be processed. Is there any updates coming soon for Epic v2 chip support?

Thanks!

**Comment by CPRyan** [comment]
We are modifying the code to work with EPICv2 as we speak. I hope this will be done by the end of this week. 

I will contact you once this is done. You should be able to simply update the package and rerun. 

Best, 

Calen

**Comment by CPRyan** [comment]
I have updated the package to work with EPICv2. You may need to lower proportionOfProbesRequired = to below 0.8, depending on how many probes you are missing. EPICv2 lacks some probes that are on v1, but this has minimal effects on the estimates from what we've seen. Please let me know if you are having trouble.
