### ISSUE TITLE
repeated measures of DNAm in data

### ISSUE THREAD

**Issue by stn013** [danbelsky/DunedinPACE#27]
Hello,

I have a dataset that includes participants who may have multiple DNAm measures, for example participant 12 has DNAm measured at times 1, 2, and 3 whereas participant 24 has DNAm measured at time 1, etc. The resulting "betas" object has some duplicated rows but different values for the CpGs. After using PACEProjector() the estimated DunedinPACE is identical for every instance of particpant 12 in the output vector from PACEProjector(). How should I approach this? Should I create new rownames for the beta object so they are all unique e.g., "participant_12_time1", "participant_12_time2", and so on?

**Comment by CPRyan** [comment]
@lemonlogic2023 

It sounds like your input data is not properly formatted. The PACEProjector function requires samples to be columns, and rows to be probes (cg#). 

Have a look at the vignette to see how to structure your input data. Update and install the package with vignette set to TRUE. 

`devtools::install_github("danbelsky/DunedinPACE", build_vignettes = TRUE)`

Then, open and view the vignette in your browser window: 

`vignette("DunedinPACE")` 

You can see (and run yourself) the example data to see what is required. If you match that input format, that should fix the issue. If not, and you are still getting identical values for replicate samples, we can troubleshoot further. Reopen this issue or contact me directly to sort through this.
