### ISSUE TITLE
Install with build_vignettes = TRUE fails

### ISSUE THREAD

**Issue by DanielEWeeks** [danbelsky/DunedinPACE#28]
Installing with `build_vignettes = TRUE` as instructed in the README.md fails as follows for me:

```
> devtools::install_github("danbelsky/DunedinPACE", build_vignettes = TRUE)
...
   --- re-building ‘DunedinPACE.Rmd’ using rmarkdown
   
   Quitting from lines 36-41 [unnamed-chunk-2] (DunedinPACE.Rmd)
   Error: processing vignette 'DunedinPACE.Rmd' failed with diagnostics:
   error in evaluating the argument 'x' in selecting a method for function 'assay': object 'example_betas' not found
   --- failed re-building ‘DunedinPACE.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘DunedinPACE.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
```

**Comment by DanielEWeeks** [comment]
Maybe this isn't working because the `example_betas` data file should have been placed in a folder named `data` instead of in a folder named `Data`?

See [Section 7.1: Exported data](https://r-pkgs.org/data.html#sec-data-data) of the R Packages book.

**Comment by CPRyan** [comment]
Hi Daniel - thanks for the feedback. I'm not sure why it is being uploaded as "Data" when on my development version of the package I have the folder as "data". In any case, the package should be all caught up with any branches now. I managed to install and run the vignette on my machine. Would you mind trying to reinstall and letting me know if the issue persists?
<img width="1171" alt="Screen Shot 2023-10-24 at 3 58 38 PM" src="https://github.com/danbelsky/DunedinPACE/assets/17647405/6be2662d-20d4-48bb-bb7a-b59e416e0db1">

**Comment by DanielEWeeks** [comment]
Installing with vignette building via the 

```
devtools::install_github("danbelsky/DunedinPACE", build_vignettes = TRUE)
```

works fine on my Mac but fails on our Linux cluster.  

To figure out why, look at what happens if I try to do a manual install on the Linux machine:

```
$ git clone https://github.com/danbelsky/DunedinPACE.git
$ ls DunedinPACE/
Data  DESCRIPTION  DunedinPACE.Rproj  LICENSE  man  NAMESPACE  R  README.md  vignettes
$  R CMD INSTALL DunedinPACE
$ ls /home/weeks/R/x86_64-pc-linux-gnu-library/4.1/DunedinPACE/
DESCRIPTION  help  html  INDEX  LICENSE  Meta  NAMESPACE  R
```

Observe that the 'Data' folder is not installed, presumably because our Linux machine has a case-sensitive disk and the R CMD INSTALL command is expecting the data folder to be named "data' instead of "Data", so it doesn't copy it over.

But on my Mac, the 'data' folder was installed when I used the `devtools::install_github` command:

```
$ ls /Users/dweeks/Library/R/arm64/4.2/library/DunedinPACE/
DESCRIPTION	LICENSE		NAMESPACE	data/		help/
INDEX		Meta/		R/		doc/		html/
```

Probable solution: Rename the 'Data' folder to 'data' instead in your GitHub repository.

**Comment by CPRyan** [comment]
Thanks for your input Daniel. For some reason, this folder name is resistant to change. If I clone the repo to my local computer, change Data/data, then push, they repo stays as Data. I'll keep troubleshooting this. In the meantime, if you want to get working with DunedinPACE, you might consider dropping the vignette altogether. 

`devtools::install_github("danbelsky/DunedinPACE", build_vignettes = FALSE)`

I apologize for the bug and hope you are able to work around the vignette issue in the meantime.

**Comment by DanielEWeeks** [comment]
Saw this suggestion on StackOverflow - maybe this would work?

```
git mv Data tmp
git mv tmp data
```

**Comment by CPRyan** [comment]
Thanks Daniel. After trying several other approaches, this worked. Hopefully this will install the vignette correctly in Linux now.

**Comment by CPRyan** [comment]
Let me know if this works and I'll close the issue.

**Comment by DanielEWeeks** [comment]
Yes, the installation now works on our Linux cluster.

**Comment by CPRyan** [comment]
Great, thanks again for your feedback and troubleshooting Daniel.
