### ISSUE TITLE
object 'noob_betas' not found

### ISSUE THREAD

**Issue by nskvir** [danbelsky/DunedinPACE#34]
Hi there, 

When I initially tried to install your package, I received the following error message: 

Quitting from lines 58-59 [unnamed-chunk-4] (DunedinPACE.Rmd)
   Error: processing vignette 'DunedinPACE.Rmd' failed with diagnostics:
   object 'noob_betas' not found
   --- failed re-building 'DunedinPACE.Rmd'
   
   SUMMARY: processing the following file failed:
     'DunedinPACE.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted

I changed the build_vignettes argument to FALSE, which allowed me to install the package, but when running the PACEProjector() command, I again got the following error: 

Loading required namespace: preprocessCore
Error in PACEProjector(betas) : object 'noob_betas' not found

Is it possible there is a missing file somewhere in the repo? Is this an issue on my end?

Thanks!

**Comment by ejh243** [comment]
I have this same issue, I think the error is introduced in the recent commit, the `noob_betas `object comes out of nowhere and I wonder if it should be `betas`?

**Comment by CPRyan** [comment]
Thank you for bringing this to my attention. It should be resolved now.
